/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/lessons/{module_id}/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_api_courses__course_id__lessons__module_id___lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/pages/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_api_courses__course_id__pages__page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/quizzes/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Module Quiz */
        get: operations["get_module_quiz_api_courses__course_id__quizzes__module_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam */
        get: operations["get_exam_api_courses__course_id__exam_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Quiz */
        post: operations["submit_quiz_api_quizzes_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/lessons/{course_id}/{module_id}/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Lesson */
        post: operations["complete_lesson_api_progress_lessons__course_id___module_id___lesson_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/position/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Position */
        put: operations["save_position_api_progress_position__course_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/attempts/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attempts */
        get: operations["list_attempts_api_progress_attempts__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Reset Course */
        delete: operations["reset_course_api_progress_courses__course_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Progress */
        get: operations["export_progress_api_progress_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Content Health */
        get: operations["content_health_api_health_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttemptSummary */
        AttemptSummary: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "module" | "exam";
            /** Module Id */
            module_id?: string | null;
            /** Total Questions */
            total_questions: number;
            /** Correct Count */
            correct_count: number;
            /** Score Percent */
            score_percent: number;
            /** Passed */
            passed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Results */
            results: components["schemas"]["QuestionResult"][];
        };
        /** ContentErrorOut */
        ContentErrorOut: {
            /** Course Id */
            course_id: string;
            /** Location */
            location: string;
            /** Message */
            message: string;
        };
        /** ContentHealth */
        ContentHealth: {
            /** Ok */
            ok: boolean;
            /** Course Count */
            course_count: number;
            /** Errors */
            errors: components["schemas"]["ContentErrorOut"][];
            /** Warnings */
            warnings: components["schemas"]["ContentErrorOut"][];
        };
        /** CourseDetail */
        CourseDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Tags */
            tags: string[];
            /** Level */
            level: string;
            /** Modules */
            modules: components["schemas"]["ModuleDetail"][];
            /** Has Cheatsheet */
            has_cheatsheet: boolean;
            /** Has Glossary */
            has_glossary: boolean;
            /** Has Exam */
            has_exam: boolean;
            /** Exam Passed */
            exam_passed: boolean;
            /** Exam Best Score */
            exam_best_score?: number | null;
            /** Progress Percent */
            progress_percent: number;
            /** Status */
            status: string;
            resume?: components["schemas"]["ResumePosition"] | null;
        };
        /** CourseSummary */
        CourseSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Tags */
            tags: string[];
            /** Level */
            level: string;
            /** Module Count */
            module_count: number;
            /** Lesson Count */
            lesson_count: number;
            /** Progress Percent */
            progress_percent: number;
            /** Status */
            status: string;
            resume?: components["schemas"]["ResumePosition"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LessonDetail */
        LessonDetail: {
            /** Course Id */
            course_id: string;
            /** Module Id */
            module_id: string;
            /** Lesson Id */
            lesson_id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Completed */
            completed: boolean;
            prev?: components["schemas"]["StepLink"] | null;
            next?: components["schemas"]["StepLink"] | null;
        };
        /** LessonProgressOut */
        LessonProgressOut: {
            /** Course Id */
            course_id: string;
            /** Module Id */
            module_id: string;
            /** Lesson Id */
            lesson_id: string;
            /** Completed */
            completed: boolean;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** LessonRef */
        LessonRef: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Completed */
            completed: boolean;
        };
        /** ModuleDetail */
        ModuleDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Lessons */
            lessons: components["schemas"]["LessonRef"][];
            /** Has Quiz */
            has_quiz: boolean;
            /** Quiz Passed */
            quiz_passed: boolean;
            /** Quiz Best Score */
            quiz_best_score?: number | null;
        };
        /** PageDetail */
        PageDetail: {
            /** Course Id */
            course_id: string;
            /** Page */
            page: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** PositionInput */
        PositionInput: {
            /** Module Id */
            module_id: string;
            /** Lesson Id */
            lesson_id: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Course Id */
            course_id: string;
            /** Module Id */
            module_id: string;
            /** Lesson Id */
            lesson_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProgressExport */
        ProgressExport: {
            /** User Id */
            user_id: string;
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
            /** Lessons */
            lessons: components["schemas"]["LessonProgressOut"][];
            /** Attempts */
            attempts: components["schemas"]["AttemptSummary"][];
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
        };
        /** QuestionResult */
        QuestionResult: {
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Selected */
            selected: string[];
            /** Correct Answer */
            correct_answer: string[];
            /** Is Correct */
            is_correct: boolean;
            /** Explanation */
            explanation: string;
        };
        /** QuizPublic */
        QuizPublic: {
            /** Course Id */
            course_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "module" | "exam";
            /** Module Id */
            module_id?: string | null;
            /** Title */
            title: string;
            /** Pass Score */
            pass_score: number;
            /** Questions */
            questions: components["schemas"]["QuizQuestionPublic"][];
        };
        /** QuizQuestionPublic */
        QuizQuestionPublic: {
            /** Index */
            index: number;
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Multiple */
            multiple: boolean;
        };
        /** QuizResult */
        QuizResult: {
            /** Attempt Id */
            attempt_id: number;
            /** Course Id */
            course_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "module" | "exam";
            /** Module Id */
            module_id?: string | null;
            /** Total Questions */
            total_questions: number;
            /** Correct Count */
            correct_count: number;
            /** Score Percent */
            score_percent: number;
            /** Passed */
            passed: boolean;
            /** Pass Score */
            pass_score: number;
            /** Results */
            results: components["schemas"]["QuestionResult"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuizSubmission */
        QuizSubmission: {
            /** Course Id */
            course_id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "module" | "exam";
            /** Module Id */
            module_id?: string | null;
            /** Answers */
            answers: string[][];
        };
        /** ResumePosition */
        ResumePosition: {
            /** Module Id */
            module_id: string;
            /** Lesson Id */
            lesson_id: string;
            /** Lesson Title */
            lesson_title: string;
        };
        /** StepLink */
        StepLink: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "lesson" | "quiz" | "exam";
            /** Module Id */
            module_id?: string | null;
            /** Lesson Id */
            lesson_id?: string | null;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"][];
                };
            };
        };
    };
    get_course_api_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_courses__course_id__lessons__module_id___lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                module_id: string;
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_courses__course_id__pages__page__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                page: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_module_quiz_api_courses__course_id__quizzes__module_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_api_courses__course_id__exam_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_quiz_api_quizzes_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_lesson_api_progress_lessons__course_id___module_id___lesson_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                module_id: string;
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_position_api_progress_position__course_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attempts_api_progress_attempts__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_course_api_progress_courses__course_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_progress_api_progress_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressExport"];
                };
            };
        };
    };
    content_health_api_health_content_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentHealth"];
                };
            };
        };
    };
    ping_api_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
